/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chrisdaw_samFastqIO_CWorker */

#ifndef _Included_chrisdaw_samFastqIO_CWorker
#define _Included_chrisdaw_samFastqIO_CWorker
#ifdef __cplusplus
extern "C" {
#endif
#undef chrisdaw_samFastqIO_CWorker_MAX_WORKER_THREADS
#define chrisdaw_samFastqIO_CWorker_MAX_WORKER_THREADS 10L
/*
 * Class:     chrisdaw_samFastqIO_CWorker
 * Method:    runmain
 * Signature: (I[[BII)V
 */
JNIEXPORT void JNICALL Java_chrisdaw_samFastqIO_CWorker_runmain
  (JNIEnv *, jclass, jint, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
